openapi: 3.0.0

paths:
  /pet/{petId}:
    put:
      summary: Given a user and a pet, show the pet information
      parameters:
        - name: pet_Id
          in: path
          required: true
          description: pet ID
        - name: petId
          in: path
          required: true
          description: pet ID
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::pet_Id}:function:updatePet/invocations"
        httpMethod: "POST"
        
    delete:
      summary: Edit the user and pet information
      parameters:
        - name: pet_Id
          in: path
          required: true
          description: pet ID
        - name: petId
          in: path
          required: true
          description: pet ID
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::pet_Id}:function:deletePet/invocations"
        httpMethod: "POST"