openapi: 3.0.0

paths:
  /pet/{petId}:
    get:
      summary: Given a user and a pet, show the pet information
      parameters:
        - name: pet_Id
          in: path
          required: true
          description: pet ID
        - name: petId
          in: path
          required: true
          description: pet ID
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::pet_Id}:function:getPet/invocations"
        httpMethod: "POST"
        
    put:
      summary: Edit the user and pet information
      parameters:
        - name: pet_id
          in: path
          required: true
          description: pet ID
        - name: petId
          in: path
          required: true
          description: pet ID
        
        requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                doggy:
                  type: string
                race:
                  type: string
                age:
                  type: string
                  
        x-amazon-apigateway-integration:
          type: "aws_proxy"
          uri:
            Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::pet_id}:function:putPet/invocations"
          httpMethod: "POST"