  
AWSTemplateFormatVersion : '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31

Description: HusckyApi
Resources:
  
  GetPetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getPet
      Environment:
        Variables:
          USERS_TABLE: !Ref DogsTable
      Handler: Dogs.getPet
      Runtime: python3.6
      CodeUri: package/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DogsTable
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref APIHuscky
            Path: "/pet/{petId}"
            Method: GET
            
  putPetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: putPet
      Environment:
        Variables:
          USERS_TABLE: !Ref DogsTable
      Handler: Dogs.putPet
      Runtime: python3.6
      CodeUri: package/
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref DogsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref DogsTable
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref APIHuscky
            Path: "/pet/{petId}"
            Method: PUT
  
  MyAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: my-api-gateway-9
      StageName: prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swagger.yaml
    
  DogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Dogs
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S